services:
  api:
    build: .
    container_name: gobdocs_api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      NODE_ENV: development
      PORT: ${PORT}
      DATABASE_URL: "postgresql://gobdocs:secret@db:5432/gobdocs"
      JWT_SECRET: ${JWT_SECRET}
  db:
    image: postgres:16-alpine
    container_name: gobdocs_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: gobdocs
      POSTGRES_USER: gobdocs
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - gobdocs_pgdata:/var/lib/postgresql/data

volumes:
  gobdocs_pgdata:
